Repository mathLab/PINA, pull requests merged in 2023-11, with the labels that each got.

#188 Label Tensor update
  pina/label_tensor.py
  tests/test_label_tensor.py
Labels: pr-to-review, v0.1

#195 add dataset and dataloader for sample points
  pina/__init__.py
  pina/callbacks/adaptive_refinment_callbacks.py
  pina/callbacks/optimizer_callbacks.py
  pina/dataset.py
  pina/geometry/simplex.py
  pina/label_tensor.py
  pina/loss.py
  pina/problem/abstract_problem.py
  pina/solvers/garom.py
  pina/solvers/pinn.py
  pina/solvers/solver.py
  pina/trainer.py
  setup.py
  tests/test_callbacks/test_adaptive_refinment_callbacks.py
  tests/test_callbacks/test_optimizer_callbacks.py
  tests/test_dataset.py
  tests/test_label_tensor.py
  tests/test_solvers/test_garom.py
  tests/test_solvers/test_pinn.py
Labels: pr-to-fix, v0.1

#177 Inverse problem implementation
  docs/source/_rst/_tutorial.rst
  docs/source/_rst/tutorials/tutorial7/tutorial.rst
  docs/source/_rst/tutorials/tutorial7/tutorial_files/output_21_0.png
  docs/source/_rst/tutorials/tutorial7/tutorial_files/output_8_0.png
  pina/condition.py
  pina/equation/__init__.py
  pina/equation/equation.py
  pina/equation/equation_interface.py
  pina/equation/system_equation.py
  pina/plotter.py
  pina/problem/__init__.py
  pina/problem/abstract_problem.py
  pina/problem/inverse_problem.py
  pina/problem/spatial_problem.py
  pina/problem/timedep_problem.py
  pina/solvers/pinn.py
  tutorials/README.md
  tutorials/tutorial7/data/pinn_solution_0.5_0.5
  tutorials/tutorial7/data/pts_0.5_0.5
  tutorials/tutorial7/tutorial.ipynb
  tutorials/tutorial7/tutorial.py
Labels: pr-to-fix, v0.1

#214 Update condition.py error message
  pina/condition.py
Labels: pr-to-review
