Repository mathLab/PINA, pull requests merged in 2024-03, with the labels that each got.

#252 PBC Layer
  docs/source/_rst/_code.rst
  docs/source/_rst/_tutorial.rst
  docs/source/_rst/layers/embedding.rst
  docs/source/_rst/layers/pod.rst
  docs/source/_rst/tutorials/tutorial9/tutorial.rst
  docs/source/_rst/tutorials/tutorial9/tutorial_files/tutorial_11_0.png
  docs/source/_rst/tutorials/tutorial9/tutorial_files/tutorial_13_0.png
  pina/model/layers/__init__.py
  pina/model/layers/embedding.py
  tests/test_layers/test_embedding.py
  tutorials/README.md
  tutorials/tutorial9/tutorial.ipynb
  tutorials/tutorial9/tutorial.py
Labels: pr-to-review

#242 Fixing #240 tutorial grammar
  docs/source/_rst/tutorials/tutorial1/tutorial.rst
  docs/source/_rst/tutorials/tutorial1/tutorial_files/tutorial_16_0.png
  docs/source/_rst/tutorials/tutorial1/tutorial_files/tutorial_23_0.png
  docs/source/_rst/tutorials/tutorial1/tutorial_files/tutorial_23_1.png
  docs/source/_rst/tutorials/tutorial1/tutorial_files/tutorial_25_0.png
  pina/meta.py
  tutorials/tutorial1/tutorial.ipynb
  tutorials/tutorial1/tutorial.py
  tutorials/tutorial2/tutorial.ipynb
  tutorials/tutorial2/tutorial.py
  tutorials/tutorial3/tutorial.ipynb
  tutorials/tutorial3/tutorial.py
  tutorials/tutorial4/tutorial.ipynb
  tutorials/tutorial4/tutorial.py
  tutorials/tutorial5/tutorial.ipynb
  tutorials/tutorial5/tutorial.py
  tutorials/tutorial6/tutorial.ipynb
  tutorials/tutorial6/tutorial.py
  tutorials/tutorial7/tutorial.ipynb
  tutorials/tutorial7/tutorial.py
  tutorials/tutorial8/tutorial.ipynb
  tutorials/tutorial9/tutorial.ipynb
  tutorials/tutorial9/tutorial.py
Labels: pr-to-review, tutorials

#230 Added Averaging Neural Operator with tests and a tutorial
  docs/source/_rst/_code.rst
  docs/source/_rst/layers/avno_layer.rst
  docs/source/_rst/models/avno.rst
  pina/model/__init__.py
  pina/model/avno.py
  pina/model/layers/__init__.py
  pina/model/layers/avno_layer.py
  tests/test_model/test_avno.py
Labels: enhancement, pr-to-review

#267 Causal PINN
  pina/solvers/__init__.py
  pina/solvers/pinns/causalpinn.py
  tests/test_solvers/test_causalpinn.py
Labels: pr-to-fix
