Repository mathLab/PINA, pull requests merged in 2025-09, with the labels that each got.

#625 simplify kwargs logic for equations
  pina/equation/equation.py
  pina/solver/physics_informed_solver/pinn_interface.py
Labels: pr-to-review

#633 fix tensor getitem in graph_dataset
  pina/data/dataset.py
  tests/test_data/test_graph_dataset.py
  tests/test_solver/test_ensemble_supervised_solver.py
  tests/test_solver/test_supervised_solver.py
  tutorials/tutorial15/tutorial.ipynb
Labels: pr-to-review

#648 Pass `method` argument to `fast_laplacian`
  pina/operator.py
  tests/test_operator.py
Labels: bug, pr-to-review

#650 Fix basis device transfer in PODBlock
  pina/model/block/pod_block.py
  tests/test_block/test_pod.py
Labels: bug, pr-to-review

#645 Update `Laplace` class and add unit tests
  docs/source/_rst/equation/equation_factory.rst
  pina/equation/__init__.py
  pina/equation/equation_factory.py
  pina/problem/zoo/advection.py
  pina/problem/zoo/allen_cahn.py
  pina/problem/zoo/diffusion_reaction.py
  pina/problem/zoo/helmholtz.py
  pina/problem/zoo/poisson_2d_square.py
  tests/test_equation/test_equation_factory.py
  tests/test_problem_zoo/test_advection.py
  tests/test_problem_zoo/test_allen_cahn.py
  tests/test_problem_zoo/test_diffusion_reaction.py
  tests/test_problem_zoo/test_helmholtz.py
  tests/test_problem_zoo/test_inverse_poisson_2d_square.py
  tests/test_problem_zoo/test_poisson_2d_square.py
Labels: enhancement, pr-to-review, low priority

#654 Disable `R0903` warning in `equation_factory.py`
  pina/equation/equation_factory.py
Labels: pr-to-review
