Repository mathLab/PINA, pull requests merged in 2025-01, with the labels that each got.

#409 Update import from lightning.pytorch
  pina/callbacks/adaptive_refinment_callbacks.py
  pina/callbacks/optimizer_callbacks.py
  pina/callbacks/processing_callbacks.py
  pina/solvers/supervised.py
Labels: bug, pr-to-review

#408 Simplify LabelTensor class
  pina/label_tensor.py
  tests/test_label_tensor/test_label_tensor.py
Labels: pr-to-review

#423 Improve DataLoader performance when batch_size=None
  pina/data/data_module.py
  pina/data/dataset.py
Labels: pr-to-review, v0.2

#430 Additional improvement related to #395
  pina/label_tensor.py
  tests/test_label_tensor/test_label_tensor.py
Labels: pr-to-review

#435 Refactoring SolverInterfaces
  pina/solvers/__init__.py
  pina/solvers/rom.py
  pina/solvers/solver.py
  pina/solvers/supervised.py
  pina/utils.py
  tests/test_solvers/test_rom_solver.py
  tests/test_solvers/test_supervised_solver.py
Labels: pr-to-fix, v0.2
