Repository mathLab/PINA, pull requests merged in 2025-07, with the labels that each got.

#599 Fix ReadMe examples
  README.md
Labels: bug

#608 Fix switch_optimizer callback
  pina/callback/optimizer_callback.py
  tests/test_callback/test_optimizer_callback.py
Labels: bug, high priority, pr-to-review

#606 Add batching support for self-adaptive pinns
  pina/solver/physics_informed_solver/self_adaptive_pinn.py
  tests/test_solver/test_self_adaptive_pinn.py
Labels: enhancement, pr-to-review

#604 Add pirate network
  docs/source/_rst/_code.rst
  docs/source/_rst/model/block/pirate_network_block.rst
  docs/source/_rst/model/pirate_network.rst
  pina/model/__init__.py
  pina/model/block/__init__.py
  pina/model/block/pirate_network_block.py
  pina/model/pirate_network.py
  tests/test_blocks/test_pirate_network_block.py
  tests/test_model/test_pirate_network.py
Labels: enhancement, pr-to-review
