Repository mathLab/PINA, pull requests merged in 2025-03, with the labels that each got.

#474 Linear weight update callback
  pina/callback/__init__.py
  pina/callback/linear_weight_update_callback.py
  tests/test_callback/test_linear_weight_update_callback.py
Labels: enhancement, pr-to-review, v0.2

#475 Improve conditions and refactor dataset classes
  .pylintrc
  code_formatter.sh
  pina/collector.py
  pina/condition/__init__.py
  pina/condition/condition.py
  pina/condition/condition_interface.py
  pina/condition/data_condition.py
  pina/condition/domain_equation_condition.py
  pina/condition/input_equation_condition.py
  pina/condition/input_output_condition.py
  pina/condition/input_target_condition.py
  pina/data/data_module.py
  pina/data/dataset.py
  pina/graph.py
  pina/label_tensor.py
  pina/problem/abstract_problem.py
  pina/problem/zoo/inverse_diffusion_reaction.py
  pina/problem/zoo/inverse_poisson_2d_square.py
  pina/problem/zoo/supervised_problem.py
  pina/solver/garom.py
  pina/solver/physic_informed_solver/pinn_interface.py
  pina/solver/physic_informed_solver/self_adaptive_pinn.py
  pina/solver/reduced_order_model.py
  pina/solver/solver.py
  pina/solver/supervised.py
  tests/test_collector.py
  tests/test_condition.py
  tests/test_data/test_data_module.py
  tests/test_data/test_graph_dataset.py
  tests/test_data/test_tensor_dataset.py
  tests/test_problem_zoo/test_supervised_problem.py
  tests/test_solver/test_causal_pinn.py
  tests/test_solver/test_competitive_pinn.py
  tests/test_solver/test_garom.py
  tests/test_solver/test_gradient_pinn.py
  tests/test_solver/test_pinn.py
  tests/test_solver/test_rba_pinn.py
  tests/test_solver/test_reduced_order_model_solver.py
  tests/test_solver/test_self_adaptive_pinn.py
  tests/test_solver/test_supervised_solver.py
Labels: pr-to-review, v0.2

#480 Add test for supervised solver in graph-based models
  tests/test_solver/test_supervised_solver.py
Labels: pr-to-review, v0.2

#517 Bug fix and add additional tests for Dataset and DataModule
  pina/data/data_module.py
  pina/data/dataset.py
  tests/test_data/test_data_module.py
  tests/test_data/test_graph_dataset.py
Labels: bug, high priority, pr-to-review

#524 fix bug in laplace labels
  pina/operator.py
  tests/test_operator.py
Labels: pr-to-review

#522 Self-loops management in KNNGraph and RadiusGraph
  pina/graph.py
  tests/test_graph.py
Labels: bug, high priority, pr-to-review
