Repository mathLab/PINA, pull requests merged in 2025-04, with the labels that each got.

#528 Improve differential operators
  pina/operator.py
  tests/test_operator.py
Labels: enhancement, pr-to-review

#537 Update tutorial_exporter.yml
  .github/workflows/tutorial_exporter.yml
Labels: high priority, maintenance

#520 Update MultiSolverInterface
  pina/solver/physics_informed_solver/competitive_pinn.py
  pina/solver/physics_informed_solver/self_adaptive_pinn.py
  pina/solver/solver.py
Labels: bug, high priority, pr-to-review

#546 Fix `__getitem__` in LabelTensor
  pina/label_tensor.py
  tests/test_label_tensor/test_label_tensor.py
Labels: bug, high priority, pr-to-review

#552 rm py3.8, add 3.13
  .github/workflows/monthly-tagger.yml
  .github/workflows/tester.yml
  .github/workflows/tutorial_exporter.yml
  pyproject.toml
Labels: pr-to-review

#555 new readme
  README.md
  readme/API_color.png
  readme/PINA_API.png
  readme/poisson_plot.png
Labels: enhancement

#544 Update Tutorials
  docs/source/_tutorial.rst
  tutorials/README.md
  tutorials/TUTORIAL_GUIDELINES.md
  tutorials/static/API_color.png
  tutorials/static/deep_ensemble.png
  tutorials/static/logging.png
  tutorials/static/neural_operator.png
  tutorials/static/pina_logo.png
  tutorials/static/pina_wokflow.png
  tutorials/tutorial1/tutorial.ipynb
  tutorials/tutorial1/tutorial.py
  tutorials/tutorial10/tutorial.ipynb
  tutorials/tutorial10/tutorial.py
  tutorials/tutorial11/logging.png
  tutorials/tutorial11/tutorial.ipynb
  tutorials/tutorial11/tutorial.py
  tutorials/tutorial12/tutorial.ipynb
  tutorials/tutorial12/tutorial.py
  tutorials/tutorial13/tutorial.ipynb
  tutorials/tutorial13/tutorial.py
  tutorials/tutorial14/tutorial.ipynb
  tutorials/tutorial14/tutorial.py
  tutorials/tutorial15/tutorial.ipynb
  tutorials/tutorial16/tutorial.ipynb
  tutorials/tutorial17/tutorial.ipynb
  tutorials/tutorial18/tutorial.ipynb
  tutorials/tutorial19/tutorial.ipynb
  tutorials/tutorial2/tutorial.ipynb
  tutorials/tutorial2/tutorial.py
  tutorials/tutorial20/tutorial.ipynb
  tutorials/tutorial21/tutorial.ipynb
  tutorials/tutorial3/tutorial.ipynb
  tutorials/tutorial3/tutorial.py
  tutorials/tutorial4/tutorial.ipynb
  tutorials/tutorial4/tutorial.py
  tutorials/tutorial5/tutorial.ipynb
  tutorials/tutorial5/tutorial.py
  tutorials/tutorial6/tutorial.ipynb
  tutorials/tutorial6/tutorial.py
  tutorials/tutorial7/tutorial.ipynb
  tutorials/tutorial7/tutorial.py
  tutorials/tutorial8/tutorial.ipynb
  tutorials/tutorial8/tutorial.py
  tutorials/tutorial9/tutorial.ipynb
  tutorials/tutorial9/tutorial.py
Labels: pr-to-review, tutorials

#556 update doc
  docs/source/_installation.rst
  docs/source/_rst/_code.rst
  docs/source/index.rst
  docs/source/index_files/API_color.png
  docs/source/index_files/PINA_API.png
Labels: documentation
