Repository mathLab/PINA, pull requests merged in 2025-02, with the labels that each got.

#443 Solver update + weighting
  pina/loss/__init__.py
  pina/loss/scalar_weighting.py
  pina/loss/weighted_aggregation.py
  pina/loss/weighting_interface.py
  pina/problem/zoo/poisson_2d_square.py
  pina/solvers/rom.py
  pina/solvers/solver.py
  pina/solvers/supervised.py
  tests/test_weighting/test_standard_weighting.py
Labels: pr-to-review, v0.2

#450 Update Condition notation & domains import in tutorials
  tutorials/tutorial11/tutorial.ipynb
  tutorials/tutorial11/tutorial.py
  tutorials/tutorial12/tutorial.ipynb
  tutorials/tutorial12/tutorial.py
  tutorials/tutorial13/tutorial.ipynb
  tutorials/tutorial13/tutorial.py
  tutorials/tutorial2/tutorial.ipynb
  tutorials/tutorial2/tutorial.py
  tutorials/tutorial3/tutorial.ipynb
  tutorials/tutorial3/tutorial.py
  tutorials/tutorial5/tutorial.ipynb
  tutorials/tutorial5/tutorial.py
  tutorials/tutorial7/tutorial.ipynb
  tutorials/tutorial7/tutorial.py
  tutorials/tutorial8/tutorial.ipynb
  tutorials/tutorial8/tutorial.py
  tutorials/tutorial9/tutorial.ipynb
  tutorials/tutorial9/tutorial.py
Labels: v0.2

#451 Supervised Problem
  pina/problem/zoo/__init__.py
  pina/problem/zoo/supervised_problem.py
  tests/test_problem_zoo/test_supervised_problem.py
Labels: pr-to-review, v0.2

#453 Add functionalities in DataModule and data loaders + tests datasets and DataModule
  pina/data/data_module.py
  pina/trainer.py
  tests/test_data/test_datamodule.py
  tests/test_data/test_graph_dataset.py
  tests/test_data/test_tensor_dataset.py
Labels: pr-to-fix, v0.2

#456 Fix bug in Collector with Graph data
  pina/collector.py
  pina/data/data_module.py
  pina/data/dataset.py
  pina/graph.py
  pina/trainer.py
  tests/test_data/test_datamodule.py
Labels: pr-to-review, v0.2

#462 Plotter back compatibility
  pina/plotter.py
Labels: v0.2
